DEFAULT_GRID_SIZE = 8
CURRENTS = [10, 20, 30, 50, 70]

ASTROCYTES_WINDOW_LENGTH = 9
ASTROCYTES_DELAY = 3
ASTROCYTES_TIME_ABOVE_THRESHOLD = 2
NEURONS_WINDOW_LENGTH = 5
NEURONS_DELAY = 0
NEURONS_TIME_ABOVE_THRESHOLD = 1